### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by hellt** [mellowdrifter/bgpwatch#1]
Hi @mellowdrifter 
As I mentioned on twitter, I wanted to contribute automatic release build out for the `bgpwatch`.

I first wanted to add the github action with `go test` on every push to make sure that release won't be built with errors in the code, but it seems that the tests are not ready (?)

```
##[error]./attributes_test.go:88:24: not enough arguments in call to decodeIPv4NLRI
	have (*bytes.Reader)
	want (*bytes.Reader, []addr)
##[error]./attributes_test.go:289:30: not enough arguments in call to decodeMPReachNLRI
	have (*bytes.Buffer)
	want (*bytes.Buffer, []addr)
##[error]./attributes_test.go:370:30: not enough arguments in call to decodePathAttributes
	have ([]byte)
	want ([]byte, []addr)
##[error]./parameters_test.go:22:5: cannot use 0 (type int) as type [4]byte in field value
##[error]./parameters_test.go:42:5: cannot use 0 (type int) as type [4]byte in field value
```

If you have no plans to fix the tests, I will add releases CD with the tests stage skipped

**Comment by mellowdrifter** [comment]
Thanks for the fix! merged.
